googleapis/nodejs-bigquery

- samples/tables.js
Looks like tables API returns not what the samples code expect to see. - @ace-n please review if the proposed change is correct. Without this change, samples tests fail like here: https://circleci.com/gh/googleapis/nodejs-bigquery/51
> make samples work

- package.json
- samples/package.json
Bumping minor version since the package has moved from GoogleCloudPlatform to googleapis/nodejs-bigquery.
> bump version to 0.11.0 since we move to a separate repo

- src/job.js
ApiError was never being instantiated and thus the 'err' variable was always undefined. This caused issues because it would never errback.
This affected Job.on('error', ...) which in turn affected Job.promise, Table.copy, Table.copyFrom, Table.export, and Table.import.
Fixes #14
> Fix Job.poll_

- src/index.js
- system-test/bigquery.js
This issue popped up today:
```
ApiError: Syntax error: Unexpected "[" at [1:17]. If this is a table identifier, escape the name with `, e.g. `table.name` rather than [table.name].
```
\- https://circleci.com/gh/googleapis/nodejs-bigquery/183
I went through and corrected the locations where we were using the `[table]` pattern.
> System Tests: Correct table notation.

- src/table.js
One link linked to the old not-existing `Table#import` method, it had to be updated to `Table#load`.
Also updated some places saying the file and data is "imported" instead of "loaded", to be more consistent with new terminology and less confusing.
> Documentation update for the change from `import` to `loaded`

- src/index.js
- system-test/bigquery.js
- test/index.js
> fix(query): exit early when dryRun is set

- package-lock.json
- package.json
- samples/package-lock.json
- samples/package.json
- (#62, #87) Exit early when `dryRun` is set on `BigQuery#query` requests.
- (#86, #88) Support custom Job IDs
- (#81) Support Job location parameter.
> chore: prep release for 1.2.0

- src/index.js
- test/index.js
> Allow passing additional scopes via constructor options.

- src/table.js
- test/table.js
Fixes #95 
That was kind of confusing. Somewhere along the line, we switched from using the default `setMetadata` method inherited from `common.ServiceObject` to a custom method. When we switched, it looks like we forgot to remove the original `setMetadata` docs.
Then, they say we're using the `update` API, but we are actually using `PATCH`.
@callmehiphop could you verify this is all correct?
> Remove duplicate declaration of setMetadata & fix docs.

- package-lock.json
- package.json
- samples/package-lock.json
- system-test/bigquery.js
`lint` tasks started failing in nightly because new prettier minor release had an incompatible change in formatting rules. Fixing that and updating lock files to force using the new version.
> chore: fix prettier incompatibility

- .circleci/config.yml
Fixing samples tests CI broken since yesterday.
I made a mistake manually editing this config file yesterday, fixing it. `npm link` will not work using non-root account unless this variable is defined.
> chore: make samples test work

- src/index.ts
Links in the [docs](https://cloud.google.com/nodejs/docs/reference/bigquery/1.3.x/BigQuery#createJob) for specific job types are broken (reported by external user). This update should point to the correct examples.
> Fix create job links

- src/table.ts
- system-test/bigquery.ts
- test/table.ts
Fixes #8 
**This would be a breaking change**
Currently, if you call `table.createWriteStream()`, the stream will emit "complete" with a Job object. You can then use that Job object to assign event handlers, as usual with an LRO. Judging from #8, I'm not sure this pattern is clear to the users. And aside from that, I'm not sure what we're doing is ideal, either.
Ideally, we would not emit "complete" until the Job finished, instead of making the user do it manually. This PR shows how easy it would be for us to implement. However, I *believe* this would be a breaking change, although it's hard to say if it's actually a bugfix.
I'm leaving this open for discussion on how we should handle this. Please share your thoughts!
---
```js
table.createWriteStream(...)
.on('complete', job => {
job …
```
> wait for job result before emitting complete.

- system-test/bigquery.ts
> fix: (tests) Use a filter to locate datasets used in tests.

- samples/tables.js
Removes the assert statements inside the samples because they are unnecessary and cause the sample to not be copy/paste runnable because assert was defined outside the samples.
> Remove asserts in samples

- system-test/bigquery.ts
An argument isn't actually required to `file.createWriteStream()`, but CI is failing: https://circleci.com/gh/googleapis/nodejs-bigquery/4374, which is blocking #190.
> Pass an empty object.

- samples/system-test/tables.test.js
- samples/tables.js
This PR:
+ Adds load truncate samples for Orc and Parquet file formats
+ Adds load, load autodetect, and load truncate samples for JSON
+ Updates Orc and Parquet samples to not specify schema. The schema is inferred for these formats, so it should not be supplied (sources: [parquet schemas](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-parquet#parquet_schemas), [orc schemas](https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-orc#orc_schemas))
> BigQuery Orc & Parquet Samples

- samples/datasets.js
- samples/queries.js
- samples/quickstart.js
- samples/tables.js
Mostly doing this to start a conversation :) What do y'all think of using async/await in our samples?  I figure, we tell people to start with the latest LTS version of nodejs, which is 8 at this stage 🤷‍♂️  Node.js 6 is 6 months from death, so I don't feel too bad doing this just in the samples. 
Thoughts?
@googleapis/node-team @fhinkel @ace-n
> Use async/await in samples

- samples/queries.js
- samples/system-test/queries.test.js
Python canonicals:
+ [simple app](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/bigquery/cloud-client/simple_app.py)
+ [query](https://github.com/googleapis/google-cloud-python/blob/ca71e4b1325e5add1438817bcf070211ce5095f2/bigquery/docs/snippets.py#L2084)
+ [query - disable cache](https://github.com/googleapis/google-cloud-python/blob/ca71e4b1325e5add1438817bcf070211ce5095f2/bigquery/docs/snippets.py#L2653)
> Refactor query samples to follow python canonical and add disable cache sample

- .eslintignore
- README.md
- benchmark/bench.ts
- package.json
- samples/datasets.js
- samples/queries.js
- samples/quickstart.js
- samples/system-test/datasets.test.js
- samples/system-test/quickstart.test.js
- samples/system-test/tables.test.js
- samples/tables.js
- src/dataset.ts
- src/index.ts
- src/job.ts
- src/table.ts
- system-test/bigquery.ts
- test/index.ts
- test/job.ts
- test/table.ts
BREAKING CHANGE: The import style of this library has been changed to be es module compatible.
```js
const BigQuery = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
```
```js
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery();
```
> refactor(typescript): convert index to es module

- src/index.ts
Fixes #269 (it's a good idea to open an issue first for discussion)
- [n/a] Code coverage does not decrease (if any source code was changed)
- [n/a] Appropriate docs were updated (if necessary)
> Changing import of Big from big.js so it doesn't use default

- package.json
- samples/package.json
- samples/system-test/.eslintrc.yml
- samples/system-test/datasets.test.js
- samples/system-test/queries.test.js
- samples/system-test/quickstart.test.js
- samples/system-test/tables.test.js
Fixes #[Convert all sample tests to mocha](https://github.com/googleapis/google-cloud-node/issues/2865) (it's a good idea to open an issue first for discussion)
> nodejs-bigquery - convert samples test ava to mocha

- src/index.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> docs: Improve timestamp documentation.

- samples/queries.js
The bigquery_simple_app_all region tag starts inside the function, so it should end inside the function. Otherwise the indentation and bracket matching are messed up when it's rendered in the docs.
> BigQuery: Fix region tag placement typo

- src/dataset.ts
- src/index.ts
- src/job.ts
- src/table.ts
during typescript compilation, the comments above the first overload gets stripped off. The doc comments need to be placed right above the last overload.
> fix(docs): move comments above last overload

- src/dataset.ts
- src/table.ts
because otherwise, we get syntax error messages when we try to import bigquery in another project
Fixes #299 (it's a good idea to open an issue first for discussion)
The `npm run lint` command has errors but not explicitly in the part I've modified:
```
❯ npm run lint
> @google-cloud/bigquery@2.0.3 lint /Users/bchhun/projects/nodejs-bigquery
> gts check && eslint samples/
/Users/bchhun/projects/nodejs-bigquery/samples/datasets.js
21:30  error  "@google-cloud/bigquery" is not found  node/no-missing-require
41:30  error  "@google-cloud/bigquery" is not found  node/no-missing-require
64:30  error  "@google-cloud/bigquery" is not found  node/no-missing-require
/Users/bchhun/projects/nodejs-bigquery/samples/queries.js
22:30  error  "@google-cloud/bigquery" is not found  node/no-missing-require …
```
> fix(ts): explicit usage of Duplex

- CHANGELOG.md
- package.json
- samples/package.json
As with any changes in types, I'm a little held back whether it should qualify as a patch vs a minor release. Please let me know if a patch release here doesn't make sense.
> Release @google-cloud/bigquery v2.0.4

- src/index.ts
- test/index.ts
Fixes #303 
In a stream, we-- y'know what, @oliverwoodings explained it best: https://github.com/googleapis/nodejs-bigquery/issues/303#issuecomment-452288078
> - My code calls `bigquery.createQueryStream()` with a query. Note that this function has been wrapped by @google-cloud/paginator
> - This calls `queryAsStream_` (https://github.com/googleapis/nodejs-bigquery/blob/master/src/index.ts#L1515), which ends up calling `createQueryJob`
> - After we have a job, we call `job.getQueryResults` (https://github.com/googleapis/nodejs-bigquery/blob/master/src/index.ts#L1505).
> - After getting the job status, the job i'm running hasn't completed, so we call back with no rows and no page token (https://github.com/googleapis/nodejs-bigquery/blob/master/src/job.ts#L418-L428)
> - The `callback` given …
> fix: correctly iterate query results within stream

- src/table.ts
Fixes #330
- [] Appropriate docs were updated (if necessary)
> fix(types): add missing parameters (selectedFields, startIndex) in table.getRows() options

- src/table.ts
- test/table.ts
Previously, only a string containing the view definition query could be provided. This allows an object, as described in the API documentation: https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource.
Fixes #332
> fix(types): Allows views to be configured using an object or a string

- system-test/bigquery.ts
We're seeing a bunch of seemingly random 404 errors in our CI system test job. I believe this is because we now have to 2 system-test jobs and our test prefix is not unique. I was going to use `uuid` but doing so puts us over the character limit.
> chore: make test prefix unique per run

- src/table.ts
The `writeDisposition` field for interface `JobLoadMetadata` appears to have been defined incorrectly; it does not belong under `timePartitioning`.
Typescript fails to compile if I define it under the root, but works as expected if I cast the options to `any` like so:
```javascript
new BigQuery({ projectId: "my-project-id" })
.dataset("my_dataset")
.table("my_table")
.load("my_file.csv", {
format: "csv",
writeDisposition: "WRITE_TRUNCATE",
} as any);
```
See:
https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs#configuration.load
> fix(types): move JobLoadMetadata writeDisposition

- .cloud-repo-tools.json
- README.md
- package.json
- samples/README.md
- samples/createDataset.js
- samples/deleteDataset.js
- samples/listDatasets.js
- samples/quickstart.js
- samples/test/datasets.test.js
- system-test/bigquery.ts
So... I made a few mistakes. During the code review of #368, a few things slipped:
1. Renames the sample files from `bigquery_dataset_bleh.js` to `createDataset.js`
1. Moves the region tags *inside* of the function definition, to match the rubric
1. Update `cloud-repo-tools.json` to include the new samples
1. Runs the repo-tools generation step to update the documentation
> fix: update samples and docs to match rubric

- system-test/bigquery.ts
Fixes #375 
Since we refactored our strategy for dealing with lingering resources, sometimes `nextQuery` will be populated with a page of resources from a different test run.
> testing: remove nextQuery assertion

- src/table.ts
> docs(table): link to upstream limit docs

- system-test/bigquery.ts
The timestamps we were using to test against were recently converted to structs (essentially protobuf timestamps), so this just updates said tests to query in the same fashion as the `DATE`/`TIME`/`DATETIME` tests
> fix(tests): update TIMESTAMP param tests

- src/job.ts
- test/job.ts
Fixes #329
Would like some confirmation from a BQ team member on this one.
> fix(job): check for `errorResult` when polling jobs

- package.json
- src/dataset.ts
- src/index.ts
- src/job.ts
- src/table.ts
- src/types.d.ts
- system-test/bigquery.ts
- test/dataset.ts
- test/index.ts
- test/table.ts
Fixes #332
This basically rewrites all the types. Pretty much every request/response interface was missing fields and every callback/response returned `request.Response` which we don't return anywhere.
~In an effort to **not** make breaking changes, I've kept all type names and duplicate types in tact.~
> fix(ts): provide complete and correct types

- src/index.ts
- src/table.ts
- system-test/.eslintrc.yml
- system-test/bigquery.ts
- test/index.ts
Trying to locate which portions of code need to be touched. tests totally failing! 
Just seeking feedback on how this should actually be done.
> feat(geo): add support for geography

- src/table.ts
Looks like the latest `arrify` types are causing an issue for us.
> refactor(ts): cast arrified rows

- src/table.ts
- test/table.ts
Fixes #408
Drop `autoCreate` param in favor of `schema`
> refactor: drop `autoCreate` in table.insert() in favor of `schema`

- package.json
- src/dataset.ts
- src/index.ts
- src/model.ts
- src/types.d.ts
- system-test/bigquery.ts
- test/dataset.ts
- test/model.ts
This adds Dataset Model support.
> feat(model): dataset model support

- package.json
- src/index.ts
- src/table.ts
- test/index.ts
- test/table.ts
This lets developers provide an api endpoint to override the backend service Url.
> feat: accept apiEndpoint override

- src/job.ts
- test/job.ts
> fix(job): remove job instance from request params

- src/table.ts
- test/table.ts
> feat(table): support all sourceFormat types

- src/index.ts
- test/index.ts
- test/table.ts
This change updates the root url for requests from `www.googleapis.com` to `bigquery.googleapis.com`.
> fix: update root url to `bigquery.googleapis.com`

- package.json
- src/table.ts
- test/bigquery.ts
- test/table.ts
Breaking change to fix #640:
- `createLoadJob` now only returns a promise (or handles the callback), and provides the completed job response. in some signatures this used to return a Writable stream
- added `createLoadJobStream` to explicitly return the Writable without any async operations, unless the writable is specifically desired by the consumer, `createLoadJob` is recommended.
fix!(table): createLoadJobStream sync returns a stream, createLoadJob always returns a job #640
Fixes #640 🦕
> refactor!: don't return Stream from createLoadJob

- src/table.ts
> fix(docs): link for job configuration load

- test/bigquery.ts
- test/dataset.ts
- test/job.ts
- test/table.ts
I'm not 100% sure why we suddenly started getting these failures (there hasn't been an update to typescript recently, which would seem like it would be the natural culprit).
Regardless, this approach seemed reasonable to me to better hint to the compiler that we have added `calledWith_` to our objects in test.
fixes #691
> test: provide hint that calledWith_ exists on stubbed objects

- src/table.ts
> fix(docs): configuration.copy link

- system-test/bigquery.ts
This refactor adds logic to check the existence of a stale testing dataset before attempting to delete it. This should fix tests that are failing due to parallel CI test runs attempting to delete the same resource.
🦕
> test: refactors system test deleteDatasets()
