googleapis/nodejs-bigquery

src/table.js, test/table.js
This commit got lost because it was checked in after I forked the code into the new repo. Putting the change back here.
[#1041](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1041) Generate insertId if not provided.
=> generate insertId if not provided

samples/README.md, samples/queries.js, samples/system-test/queries.test.js
- Add additional region tags to support tutorial rewrite.
- Use more direct map for printing results.
- Use more relevant query from public datasets.
=> Samples: rewrite simple app tutorial.

system-test/data/kitten-test-data.json
=> Correct value for TIMESTAMP in test data.

src/dataset.js, src/index.js
=> rename query parameter to options for non-query methods

samples/system-test/tables.test.js, samples/tables.js, src/table.js, system-test/bigquery.js, test/table.js
=> rename import/export to load/extract

src/index.js
=> redirect users to startQuery for manual pagination

src/job.js
Please check if the update is valid.
=> more description for nextQuery

package.json, samples/README.md, samples/package.json
Release notes coming in the GitHub UI.
Toward #47.
=> Update version number, regen scaffolding.

samples/queries.js, src/dataset.js, src/index.js, src/job.js, src/table.js, system-test/bigquery.js, test/dataset.js, test/index.js, test/table.js
=> rename job methods from start{Type} to create{Type}Job

.cloud-repo-tools.json, README.md, package.json, samples/README.md, samples/package.json
BigQuery is ready for GA, so let's release v1.0.0.
=> release 1.0.0

src/table.js
bigquery has no method table, but dataset does.
Fixes internal bug
=> Update examples that had bigquery.table

src/index.js, src/table.js, system-test/bigquery.js, test/index.js, test/table.js
=> feat(job): support custom ids

samples/queries.js, samples/system-test/tables.test.js, samples/tables.js
=> Updates region tags to standard and deletes unused region tags

samples/system-test/tables.test.js, samples/tables.js, src/table.js, test/table.js
=> Support parquet file format.

package-lock.json, samples/package-lock.json
Updating lock files. We need Renovate! Arggghhh.
=> chore: lock files

src/index.js, src/job.js, test/index.js, test/job.js
=> Correctly pass `autoPaginate: false` to query methods.

samples/system-test/datasets.test.js, samples/system-test/quickstart.test.js, samples/system-test/tables.test.js
This should fix the nightly tests 😄
=> fix: fix the samples tests

src/index.ts
=> fix: (docs): Correct query syntax.

samples/README.md, samples/system-test/tables.test.js, samples/tables.js
=> chore(samples): Remove unused BigQuery samples and fix comment typos

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/bigquery v2.0.1

src/table.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> docs: Improve documentation for load method

CHANGELOG.md, package.json, samples/package.json
=> feat: release @google-cloud/bigquery v2.0.2

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/bigquery v2.0.3

src/index.ts, test/index.ts
=> fix: createQueryJob should accept pageToken

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/bigquery v2.0.5

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/bigquery v2.0.6

system-test/bigquery.ts
Reverts googleapis/nodejs-bigquery#363
RE: https://github.com/googleapis/nodejs-bigquery/pull/363#issuecomment-468364958
I'm working on it :)
=> Revert "chore: make test prefix unique per run"

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/bigquery v2.1.0

src/index.ts, test/index.ts
=> fix: correctly encode nested custom date/time parameters

samples/browseRows.js, samples/copyTable.js, samples/createDataset.js, samples/createTable.js, samples/deleteDataset.js, samples/deleteTable.js, samples/extractTableToGCS.js, samples/insertRowsAsStream.js, samples/listDatasets.js, samples/listTables.js, samples/loadCSVFromGCS.js, samples/loadCSVFromGCSAutodetect.js, samples/loadCSVFromGCSTruncate.js, samples/loadJSONFromGCS.js, samples/loadJSONFromGCSAutodetect.js, samples/loadJSONFromGCSTruncate.js, samples/loadLocalFile.js, samples/loadOrcFromGCSTruncate.js, samples/loadParquetFromGCSTruncate.js, samples/loadTableGCSORC.js, samples/loadTableGCSParquet.js, samples/query.js, samples/queryDisableCache.js, samples/queryParamsNamed.js, samples/queryParamsPositional.js, samples/queryStackOverflow.js, samples/quickstart.js
=> refactor(samples): add main() function wrappers to samples

src/table.ts
=> fix(types): correct  interface

src/table.ts
=> fix(table): allow for TableSchema to be used

src/index.ts, test/index.ts
=> fix: correctly encode nested struct/array params

samples/query.js
Fixes #446 (it's a good idea to open an issue first for discussion)
- ~~[ ] Tests and linter pass~~ N/A
- ~~[ ] Code coverage does not decrease (if any source code was changed)~~ N/A
=> docs(samples): reference the dataset that's actually used

samples/deleteModel.js, samples/getModel.js, samples/listModels.js, samples/listModelsStreaming.js, samples/package.json, samples/test/models.test.js, samples/updateModel.js
=> docs(samples): adds get, delete, list, update model samples

linkinator.config.json, package.json, src/dataset.ts, src/index.ts, src/model.ts, src/table.ts
Fixes #504
Looking a little better ....
=> fix(docs): fix formatting of the docs

.repo-metadata.json
=> docs: correct casing of "BigQuery"

src/bigquery.ts, test/bigquery.ts
=> fix: do not modify constructor options argument

samples/auth-user-sample/authUserFlow.js
=> chore: update region tag

samples/test/tables.test.js
=> test(samples): test all samples and not just tables

samples/createTablePartitioned.js, samples/test/tables.test.js
Fixes #697
Thanks, @toninofox!
=> fix(docs): correct createTablePartitioned sample argument

samples/test/datasets.test.js, samples/test/jobs.test.js, samples/test/models.test.js, samples/test/queries.test.js, samples/test/quickstart.test.js, samples/test/tables.test.js
Updates test resource naming to improve traceability of persistent resources 🦕
=> docs(samples): updates test resource naming to improve traceability

src/table.ts, test/table.ts
=> fix: load job to a different project ID

system-test/bigquery.ts
=> tests(system): adds check for creationTime

samples/queryParamsNamedTypes.js, samples/queryParamsPositionalTypes.js, samples/test/queries.test.js, system-test/bigquery.ts
=> docs(samples): adds sample for providing query parameter types
